FROM ubuntu:14.04.5
MAINTAINER Daniel Falkner <dafalkne@microsoft.com>
COPY bootstrap.sh /tmp/bootstrap.sh
RUN apt-get update && apt-get -y install wget ca-certificates && rm -rf /var/lib/apt/lists/*
RUN sh /tmp/bootstrap.sh
